// swift-tools-version:5.4
import PackageDescription

// SwiftPM can evaluate remote revisions with only /Package.swift in its VFS.
// Keep this declaration independent of files in the package checkout.
let openccVersion = "1.4.2" // Generated by scripts/update-opencc-resources.py.

let package = Package(
    name: "SwiftyOpenCC",
    products: [.library(name: "OpenCC", targets: ["OpenCC"])],
    targets: [
        // Copy the data folders, not a top-level "Resources" directory: that
        // directory makes an iOS bundle unsuitable for Xcode Cloud signing.
        .target(name: "OpenCC", dependencies: ["copencc"], resources: [
            .copy("Resources/Official"),
            .copy("Resources/Compatibility"),
            .copy("Resources/manifest.json")
        ]),
        .testTarget(name: "OpenCCTests", dependencies: ["OpenCC", "copencc"],
                    resources: [.copy("testcases")]),
        .target(
            name: "copencc",
            sources: [
                "source.cpp",
                "src/Config.cpp",
                "src/Conversion.cpp",
                "src/ConversionAmbiguities.cpp",
                "src/ConversionCandidates.cpp",
                "src/ConversionChain.cpp",
                "src/Converter.cpp",
                "src/Dict.cpp",
                "src/DictConverter.cpp",
                "src/DictEntry.cpp",
                "src/DictGroup.cpp",
                "src/Lexicon.cpp",
                "src/MarisaDict.cpp",
                "src/MaxMatchSegmentation.cpp",
                "src/PhraseExtract.cpp",
                "src/PipelineConverter.cpp",
                "src/PluginSegmentation.cpp",
                "src/PrefixMatch.cpp",
                "src/SingleStageConverter.cpp",
                "src/ResourceProvider.cpp",
                "src/SerializableDict.cpp",
                "src/SerializedValues.cpp",
                "src/SimpleConverter.cpp",
                "src/Segmentation.cpp",
                "src/TextDict.cpp",
                "src/UTF8StringSlice.cpp",
                "src/UTF8Util.cpp",
                "src/BinaryDict.cpp",
                "src/DartsDict.cpp",
                "marisa",

            ],
            cxxSettings: [
                .headerSearchPath("src"),
                .headerSearchPath("deps/marisa-0.3.1/include"),
                .headerSearchPath("deps/marisa-0.3.1/lib"),
                .headerSearchPath("deps/darts-clone-0.32h/include"),
                .headerSearchPath("deps/rapidjson-1.1.0"),
                .define("Opencc_BUILT_AS_STATIC"),
                .define("OPENCC_VERSION", to: "\"" + openccVersion + "\"")
            ]
        )
    ],
    cxxLanguageStandard: .cxx17
)
